### ISSUE TITLE
'+' plus icon rendered in class name

### ISSUE THREAD

**Issue by dev7ch** [jessekorzan/masonry-css-js#1]
https://github.com/jessekorzan/masonry-css-js/blob/2561b4ce6dca18fafc17c56fc937707463f6542c/src/App.js#L25

It might sth unescaped, like 
```js
`layout` + `${...}` 
```
 coz i guess the plus is not need there, right?

**Comment by jessekorzan** [comment]
LOL... that about sums up my JS skillz :) Nice catch @dev7ch

**Comment by dev7ch** [comment]
;) cheers @jessekorzan
